stark:
  account:
    environment: ${ZONE:sandbox}
    id: ${ID_ACCOUNT:6019402684170240}
    key: ${KEY:../../../../privateKey.pem}
quarkus:
  datasource:
    jdbc:
      url: ${DATABASE_URL:urlDoBanco_schema}
    db-kind: postgresql
    username: ${DATABASE_USERNAME:user}
    password: ${DATABASE_PASSWORD:password}
  hibernate-orm:
    database:
      generation: none