stark:
  account:
    environment: ${ZONE:local}
    id: ${ID_ACCOUNT:0000000000}
    key: ${KEY:local}
quarkus:
  datasource:
    jdbc:
      url: ${DATABASE_URL:urlDoBanco_schema}
    db-kind: postgresql
    username: ${DATABASE_USERNAME:user}
    password: ${DATABASE_PASSWORD:password}
  hibernate-orm:
    database:
      generation: none